
--
-- Volcado de datos para la tabla `cuenta_resultados`
--

INSERT INTO `cuenta_resultados` (`Id`, `Nivel1`, `Nivel2`, `nivel3`, `cuenta_mayor_id`, `multiplicador`) VALUES
(1, '1. INGRESOS PROPIOS DE LA ACTIVIDAD', 'A. CUOTAS DE AFILIADOS', 'A.1 RENOVACIONES SOCIOS', 16, 1),
(2, '1. INGRESOS PROPIOS DE LA ACTIVIDAD', 'A. CUOTAS DE AFILIADOS', 'A.2 NUEVOS SOCIOS', 17, 1),
(3, '1. INGRESOS PROPIOS DE LA ACTIVIDAD', 'B. APORTACIONES DE USUARIOS', 'B.1 APORTACIONES VARIAS', 18, 1),
(4, '1. INGRESOS PROPIOS DE LA ACTIVIDAD', 'B. APORTACIONES DE USUARIOS', 'B.2 INGRESOS POR TIRADAS', 99, 1),
(5, '1. INGRESOS PROPIOS DE LA ACTIVIDAD', 'C. SUBVENCIONES', 'C.1 COMUNIDAD DE MADRID', 100, 1),
(6, '1. INGRESOS PROPIOS DE LA ACTIVIDAD', 'C. SUBVENCIONES', 'C.2 AYUNTAMIENTO DE FUENLABRADA', 101, 1),
(7, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.1 PRIMAS DE SEGUROS', 110, -1),
(8, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.2 SERVICIOS BANCARIOS', 1, -1),
(9, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 2, -1),
(10, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 3, -1),
(11, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 4, -1),
(12, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 5, -1),
(13, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 6, -1),
(14, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 7, -1),
(15, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 8, -1),
(16, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 96, -1),
(17, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 9, -1),
(18, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 10, -1),
(19, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.3 OTROS SERVICIOS', 11, -1),
(20, '2. OTROS GASTOS DE LA ACTIVIDAD', 'A. SERVICIOS EXTERIORES', 'A.4 TRIBUTOS', 108, -1),
(21, '3. AMORTIZACIONES', 'A. AMORTIZACIONES DEL INMOVILIZADO MATERIAL', 'A.1 AMORTIZACIÓN ACUMULADA DE UTILLAJE', 36, -1),
(22, '3. AMORTIZACIONES', 'A. AMORTIZACIONES DEL INMOVILIZADO MATERIAL', 'A.2 AMORTIZACIÓN ACUMULADA DE MOBILIARIO', 37, -1),
(23, '3. AMORTIZACIONES', 'A. AMORTIZACIONES DEL INMOVILIZADO MATERIAL', 'A.3 AMORTIZACIÓN ACUMULADO DE OTRO INMOVILIZADO MATERIAL', 38, -1),
(24, '3. AMORTIZACIONES', 'A. AMORTIZACIONES DEL INMOVILIZADO MATERIAL', 'A.3 AMORTIZACIÓN ACUMULADO DE OTRO INMOVILIZADO MATERIAL', 39, -1),
(25, '3. AMORTIZACIONES', 'A. AMORTIZACIONES DEL INMOVILIZADO MATERIAL', 'A.3 AMORTIZACIÓN ACUMULADO DE OTRO INMOVILIZADO MATERIAL', 40, -1),
(26, '3. AMORTIZACIONES', 'A. AMORTIZACIONES DEL INMOVILIZADO MATERIAL', 'A.3 AMORTIZACIÓN ACUMULADO DE OTRO INMOVILIZADO MATERIAL', 41, -1);
