
--
-- Volcado de datos para la tabla `proveedores`
--

INSERT INTO `proveedores` (`id`, `cuenta_mayor_id`, `NIF`, `descripcion`) VALUES
(1, 98, NULL, 'Microsoft Ireland Operations Limited'),
(2, 44, NULL, 'Tubos Paris'),
(3, 45, NULL, 'Cerra Archery'),
(4, 46, NULL, 'Mercadona'),
(5, 47, NULL, 'Ferreterias  Muñoz Alvarez, S.L'),
(6, 48, NULL, 'Armeria la Caza'),
(7, 49, NULL, 'Pinturas Madrid Color'),
(8, 50, NULL, 'Centros Comerciales Carrefour S.A.'),
(9, 51, NULL, 'Plaesa'),
(10, 52, NULL, 'Leroy Merlin España S.L.U.'),
(11, 53, NULL, 'Neder Lejano, S.L. (Home Asia)'),
(12, 54, NULL, '1and1 Internet EspaÃ±a, S.L.U.'),
(13, 55, NULL, 'Digital Cake Lab. Koop, E.T.'),
(14, 56, NULL, 'Charcuteria Luis Jimenez Novo'),
(15, 57, NULL, 'Cecilio Nogal S.A.'),
(16, 58, NULL, 'Online Trademark, S.L. (Zebra Online)'),
(17, 59, NULL, 'Worten España, S.L.'),
(18, 60, NULL, 'Basabero 10T, S.L. (CashConverter)'),
(19, 61, NULL, 'Bricolaje BricoMan, S.L.U. (BricoMart)'),
(20, 62, NULL, 'Staples Productos de Oficina, S.L.U.'),
(21, 63, NULL, 'Copysell Reprografía y Artes Gráficas, S.L.'),
(22, 64, NULL, 'Inversiones Gotel, S.L. (Folder)'),
(23, 65, NULL, 'D.P.A. Loyfer, S.L.'),
(24, 66, NULL, 'NCH Stock 23, S.L.'),
(25, 67, NULL, 'Maderas y Resultantes, S.L.'),
(26, 68, NULL, 'Ferretoria ENOL, S.A.'),
(27, 69, NULL, 'Eugenio Pereda, S.A.'),
(28, 70, NULL, 'Proveedores,. Vital Archery S.L. '),
(29, 71, NULL, 'Manuel Riesgo, S.A.'),
(30, 72, NULL, 'PDRI Nuevo Decor S.L.'),
(31, 73, NULL, 'Ventanas y Compactos, S.L.'),
(32, 74, NULL, 'Ferreteria Escalona'),
(33, 75, NULL, 'Restaurante La Esquina de Avila'),
(34, 76, NULL, 'Dianas Escandell'),
(35, 77, NULL, 'Dianas IMAGO'),
(36, 78, NULL, 'VPA Business Resale S.R.L. (t-locompro.com)'),
(37, 79, NULL, 'Frugocash S.L.'),
(38, 80, NULL, 'Suministros Printer S.L.'),
(39, 81, NULL, 'Anfix Software S.L.'),
(40, 82, NULL, 'PC Componentes y Multimedia S.L.'),
(41, 83, NULL, 'Amentia Publicidad'),
(42, 84, NULL, 'AMAZON S.L.'),
(43, 85, NULL, 'Ferreteria Tropical'),
(44, 102, NULL, 'ICB Impresoras'),
(45, 103, NULL, 'GG.AA. FNAC ESPAÑA S.A.U'),
(46, 104, NULL, 'Vodafone España'),
(47, 106, NULL, 'Gamo 2 S.L.'),
(48, 105, NULL, 'Ofiarea'),
(49, 107, NULL, 'Aratz Clima S.L.'),
(50, 111, NULL, 'TROFEOS MARTINEZ'),
(51, 115, NULL, 'FEDERACION MADRILENA DE TIRO CON ARCO'),
(52, 120, NULL, 'NATURFOAM'),
(54, 118, NULL, 'FERRETERIA TROPICAL'),
(55, 119, NULL, 'CORREOS '),
(56, 121, NULL, 'ORANGE ESPAÃ‘A S.A.'),
(57, 122, NULL, 'ASADOR ERRAZKI'),
(58, 123, NULL, 'GENERICO'),
(59, 124, NULL, 'DECATHLON'),
(60, 125, NULL, 'INTURCAL S.L.');
